/**
 * Generate supabase/seed.sql from supabase/seed.rooms.json.
 *
 * Semantics: truncate-and-reload. The file deletes the reference data it
 * manages (in reverse dependency order) then inserts canonical rows. Auth-era
 * tables (check_ins, issues, votes, profiles…) are never touched, so re-running
 * the seed never destroys user-generated content.
 *
 * Run:  node scripts/gen-seed.mjs
 * Then: node scripts/apply-sql.mjs supabase/seed.sql
 */

import { readFileSync, writeFileSync } from 'node:fs';

const seed = JSON.parse(readFileSync('supabase/seed.rooms.json', 'utf8'));

// ---------------------------------------------------------------------------
// SQL literals
// ---------------------------------------------------------------------------

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const lit = (v) => {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (Array.isArray(v)) return `array[${v.map((x) => q(x)).join(', ')}]`;
  return q(v);
};
const row = (cols, vals) => `  (${vals.map(lit).join(', ')})`;
const insert = (table, cols, rows) =>
  `insert into public.${table} (${cols.join(', ')}) values\n${rows.join(',\n')};`;

// ---------------------------------------------------------------------------
// Sections — FK-safe order for inserts, reverse for deletes
// ---------------------------------------------------------------------------

const out = [];
out.push(`-- =============================================================================
-- JainSpace — canonical seed. GENERATED by scripts/gen-seed.mjs — do not edit.
-- Source: supabase/seed.rooms.json (generated_at ${seed.generated_at}).
--
-- Deletes and re-inserts REFERENCE data only (blocks, floors, rooms,
-- infrastructure, features, faculty, courses, timetable). User-generated
-- tables (profiles, check_ins, issues, votes, exceptions) are untouched.
-- =============================================================================

begin;`);

const del = (t) => `delete from public.${t};`;
out.push(`
-- Reverse-dependency deletes ----------------------------------------------
${['room_features', 'features', 'timetable_slots', 'courses', 'faculty', 'room_infrastructure', 'rooms', 'floors', 'blocks'].map(del).join('\n')}`);

// blocks
out.push(`\n-- Blocks -------------------------------------------------------------------
${insert('blocks', ['id', 'code', 'name'], seed.blocks.map((b) => row(0, [b.id, b.code, b.name])))}`);

// floors
out.push(`\n-- Floors -------------------------------------------------------------------
${insert('floors', ['id', 'block_id', 'level', 'label'], seed.floors.map((f) => row(0, [f.id, f.block_id, f.level, f.label])))}`);

// rooms
out.push(`\n-- Rooms --------------------------------------------------------------------
${insert(
  'rooms',
  ['id', 'code', 'slug', 'name', 'block_id', 'floor_id', 'wing', 'category', 'capacity', 'description', 'directions', 'is_accessible', 'is_bookable', 'is_active', 'catalog_amenities', 'catalog_best_for'],
  seed.rooms.map((r) => row(0, [r.id, r.code, r.slug, r.name, r.block_id, r.floor_id, r.wing, r.category, r.capacity, r.description, r.directions, r.is_accessible, r.is_bookable, r.is_active, r.catalog_amenities, r.catalog_best_for])),
)}`);

// infrastructure
out.push(`\n-- Room infrastructure ------------------------------------------------------
${insert(
  'room_infrastructure',
  ['room_id', 'sockets_total', 'sockets_working', 'has_ac', 'ac_type', 'ac_setpoint_c', 'has_projector', 'has_smart_board', 'has_whiteboard', 'has_natural_light', 'wifi_band', 'wifi_mbps', 'wifi_label_raw', 'noise_vibe', 'comfort_score'],
  seed.infrastructure.map((i) => row(0, [i.room_id, i.sockets_total, i.sockets_working, i.has_ac, i.ac_type, i.ac_setpoint_c, i.has_projector, i.has_smart_board, i.has_whiteboard, i.has_natural_light, i.wifi_band, i.wifi_mbps, i.wifi_label_raw, i.noise_vibe, i.comfort_score])),
)}`);

// features + room_features
out.push(`\n-- Canonical feature vocabulary --------------------------------------------
${insert('features', ['id', 'slug', 'label', 'kind'], seed.features.map((f) => row(0, [f.id, f.slug, f.label, f.kind])))}`);

out.push(`\n-- Room -> feature links ----------------------------------------------------
${insert('room_features', ['room_id', 'feature_id'], seed.room_features.map((rf) => row(0, [rf.room_id, rf.feature_id])))}`);

// faculty
out.push(`\n-- Faculty ------------------------------------------------------------------
${insert('faculty', ['id', 'full_name'], seed.faculty.map((f) => row(0, [f.id, f.full_name])))}`);

// courses
out.push(`\n-- Courses ------------------------------------------------------------------
${insert('courses', ['id', 'code', 'title'], seed.courses.map((c) => row(0, [c.id, c.code, c.title])))}`);

// timetable
out.push(`\n-- Timetable (recurring Mon-Fri pattern from the legacy "today" schedule) ---
${insert(
  'timetable_slots',
  ['id', 'room_id', 'course_id', 'faculty_id', 'day_of_week', 'start_time', 'end_time', 'kind', 'batch', 'title_override'],
  seed.timetable_slots.map((s) => row(0, [s.id, s.room_id, s.course_id, s.faculty_id, s.day_of_week, s.start_time, s.end_time, s.kind, s.batch, s.title_override])),
)}`);

if (seed.warnings?.length) {
  out.push(`\n-- Extractor warnings at generation time:
${seed.warnings.map((w) => `-- - ${w}`).join('\n')}`);
}

out.push(`\ncommit;\n`);

writeFileSync('supabase/seed.sql', out.join('\n'), 'utf8');
console.log(`Wrote supabase/seed.sql (${(out.join('\n').length / 1024).toFixed(1)} kB)`);
console.log(`  blocks=${seed.blocks.length} floors=${seed.floors.length} rooms=${seed.rooms.length} infra=${seed.infrastructure.length}`);
console.log(`  features=${seed.features.length} room_features=${seed.room_features.length} faculty=${seed.faculty.length} courses=${seed.courses.length} slots=${seed.timetable_slots.length}`);
